# Generated by Django 5.2.7 on 2026-04-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_invoicesequence_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
        migrations.AlterModelOptions(
            name='invoicesequence',
            options={'ordering': ['-year'], 'verbose_name': 'invoice sequence', 'verbose_name_plural': 'invoice sequences'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
    ]
