# Generated by Django 5.2.7 on 2025-12-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temporary_password_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
