# Generated by Django 5.2.7 on 2026-01-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-last_login'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
