# Generated by Django 5.2.7 on 2026-04-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-last_login'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
