# Generated by Django 5.2.7 on 2026-01-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_remove_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
